name: Test Android build
on:
  pull_request:
    paths:
      - 'android/**'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: Example
      ANDROID_NDK: $ANDROID_HOME/ndk-bundle
      ANDROID_NDK_ROOT: $ANDROID_HOME/ndk-bundle
      ANDROID_NDK_HOME: $ANDROID_NDK_ROOT
    concurrency:
      group: android-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Echo android home
        run: echo $ANDROID_HOME
      - name: Echo ndk
        run: echo $ANDROID_NDK
      - name: Install NDK
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
            ndk-bundle
            ndk;21.2.6472646
            cmake;3.10.2.4988404
      - name: Echo ndk
        run: echo $ANDROID_NDK
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install root node dependencies
        run: yarn
      - name: Install example app node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}/android
        run: ./gradlew assembleDebug --console=plain
